CHANGELOG.md
pubspec.yaml

Fix pubspec.yaml version
Closes #

Release 1.0.1

---

README.md

Added a small mention in documentation that it is possible to override the http calls done by the SDK to perform actions such as certificate pinning.
Closes #9 
README.md
Felt that it was missing, I had to dig into the SDK code to discover that it was possible to override the http calls.
I plan to have some "hidden" things behind flips and having pinning is one way to make it a bit more complex for attackers to intercept traffic. I guess this will be the same for many people with production apps.

docs: mention http fetcher and poster in README.md

---

README.md
lib/payload.dart
lib/variant.dart
test/toggle_config_test.dart
test/unleash_proxy_client_flutter_test.dart

This PR adds support of Payload object inside Variants one. Approach is similar to the Android SDK:
https://github.com/Unleash/unleash-android-proxy-sdk/blob/main/src/main/kotlin/io/getunleash/data/Variant.kt
https://github.com/Unleash/unleash-android-proxy-sdk/blob/main/src/main/kotlin/io/getunleash/data/Payload.kt
Closes #11
- payload.dart
- toggle_config_test.dart
- unleash_proxy_client_flutter_test.dart
- variant.dart
- README.md
This is my first PR to your repository, I updated the mapping, tests and a bit of documentation, feel free to add requirements

feat: added variant payload support

---

CHANGELOG.md
pubspec.yaml

feat: version bump

---

lib/metrics.dart
lib/unleash_proxy_client_flutter.dart
test/unleash_proxy_client_flutter_test.dart

Adding metrics per variant support

feat: variant metrics

---

lib/toggle_config.dart
test/pase_toggles_test.dart

Handles missing API data when parsing API response

fix: handling missing api data

---

pubspec.yaml

Updated `http` dependency to `1.1.0` to support Dart 3.0.
Updated also Dart dependency to 3.0 or later.
pubspec.yaml
Are there any issues with this dependency update?

chore: Updated `http` to 1.1.0

---

CHANGELOG.md
README.md
example/pubspec.lock
pubspec.yaml

Version bump to 1.3.0 and tiny docs update

chore: version bump

---

lib/unleash_context.dart

fix: formatting

---

lib/unleash_proxy_client_flutter.dart
test/unleash_proxy_client_flutter_test.dart

Sending environment in the URL to Unleash proxy/edge/frontend API

feat: send environment in url

---

example/lib/main.dart
example/pubspec.lock
pubspec.yaml

* updated deps to the version that keep the SDK requirements intact
* updates example code to use frontend API

chore: update deps

---

.github/workflows/add-to-project.yml

Send issues and prs info on this project to the support board.

chore: pr issues automation

---

README.md
lib/unleash_proxy_client_flutter.dart
test/unleash_proxy_client_flutter_test.dart

Ability to set a map of context fields without making separate calls for each of them and without a need to know the full context.
Inspired by this conversation and use case: https://github.com/Unleash/unleash_proxy_client_flutter/issues/29#issuecomment-1942163096

feat: ability to set multiple context fields

---

example/pubspec.lock
pubspec.yaml

Bumping dependencies with `dart fix`

chore: bump dependencies

---

pubspec.yaml

chore: bump version to 1.5.1

---

CHANGELOG.md
pubspec.yaml

chore: update changelog and bump version

---

README.md
example/pubspec.lock
pubspec.yaml

Increases supported ranges of versions for shared_preferences and uuid.
Fixes: https://github.com/Unleash/unleash_proxy_client_flutter/issues/45

chore: increase uuid and shared_preferences version ranges

---

CHANGELOG.md
README.md
example/pubspec.lock
lib/variant.dart
pubspec.yaml
test/parse_toggles_test.dart
test/unleash_proxy_client_flutter_test.dart

Fixes https://github.com/Unleash/unleash_proxy_client_flutter/issues/48
Added call of `toMap` for the Payload inside Variant.

fix: payload stringify in bootstrap

---

CHANGELOG.md
README.md
lib/metrics.dart
lib/unleash_proxy_client_flutter.dart
pubspec.yaml
test/unleash_proxy_client_flutter_test.dart

User controlled `updateToggles` and `sendMetrics` modelled after our JS proxy SDK (same behavior, same tests, same API and same docs).

feat: user controlled update toggles and send metrics

---

CHANGELOG.md
README.md
example/lib/main.dart
lib/unleash_proxy_client_flutter.dart
pubspec.yaml
test/unleash_proxy_client_flutter_test.dart

Based on findings in https://github.com/Unleash/unleash-client-java/pull/264
Previous version scheme:  `unleash-flutter@version`
New version scheme: `unleash-client-flutter:version`
Rationale: we already have established format in the backend code

chore: x-unleash-sdk version scheme

---

CHANGELOG.md
example/pubspec.lock
lib/metrics.dart
lib/unleash_proxy_client_flutter.dart
pubspec.yaml
test/unleash_proxy_client_flutter_test.dart

x- headers are deprecated (https://datatracker.ietf.org/doc/html/rfc6648). Let's use unleash- instead.

fix: drop x prefix

---

CHANGELOG.md
example/pubspec.lock
lib/unleash_proxy_client_flutter.dart
pubspec.yaml
test/unleash_proxy_client_flutter_test.dart

Closes #63 
Adds missing variant data to the impression event.

fix: add variant data to impression event

---

.github/workflows/release.yml
README.md
lib/unleash_proxy_client_flutter.dart
test/unleash_proxy_client_flutter_test.dart

This was generated by an AI agent following the instructions in the readme file.
I think it's safe to try, it just needs the secret `PUB_DEV_TOKEN` to be able to publish, but can also be run as "do not publish", which will open a PR, so we can inspect the changes before merging

chore: automate release process
